### ISSUE TITLE
Crashed on build GEOSadas with ld errors, using so libs

### ISSUE THREAD

**Issue by jing-guo** [GEOS-ESM/GEOSadas#106]
My build of GEOSadas with a tag d2d3c85 (HEAD -> feature/rtodling/GEOSadas-5_29_0) has failed.  This crash is consistent with many crashes I had in the past with different tags.  

My build was done through parallel_build.csh, with error messages:

...
> [ 27%] Building Fortran object src/Shared/@NCEP_Shared/NCEP_bufr_r8i4/CMakeFiles/NCEP_bufr_r8i4.dir/ufbmms.f.o
> ld: cannot find new/build/lib: No such file or directory
> [ 27%] Building Fortran object src/Shared/@NCEP_Shared/NCEP_bufr_r8i4/CMakeFiles/NCEP_bufr_r8i4.dir/ufbmns.f.o
> [ 27%] Linking Fortran static library ../../../../lib/libNCEP_bufr_r4i4.a
> src/Shared/@MAPL/shared/tests/CMakeFiles/MAPL.shared.tests.dir/build.make:145: recipe for target 'src/Shared/@MAPL/share
> d/tests/MAPL.shared.tests' failed
> make[2]: *** [src/Shared/@MAPL/shared/tests/MAPL.shared.tests] Error 1
> CMakeFiles/Makefile2:8521: recipe for target 'src/Shared/@MAPL/shared/tests/CMakeFiles/MAPL.shared.tests.dir/all' failed
> make[1]: *** [src/Shared/@MAPL/shared/tests/CMakeFiles/MAPL.shared.tests.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

...
> [ 29%] Linking Fortran executable ../../../../bin/zeit_ci.x
> Using pure routines.
> Using allocatable derived type array members.
> Using cray pointers.
> ld: ../../../../bin/zeit_ci.x: hidden symbol `__intel_cpu_features_init' in /usr/local/intel/2020/compilers_and_librarie
> s_2020.4.304/linux/compiler/lib/intel64/libirc.a(cpu_feature_disp.o) is referenced by DSO
> ld: final link failed: bad value
> src/Shared/@GMAO_Shared/GMAO_etc/CMakeFiles/zeit_ci.x.dir/build.make:116: recipe for target 'bin/zeit_ci.x' failed
> make[2]: *** [bin/zeit_ci.x] Error 1
> CMakeFiles/Makefile2:10304: recipe for target 'src/Shared/@GMAO_Shared/GMAO_etc/CMakeFiles/zeit_ci.x.dir/all' failed
> make[1]: *** [src/Shared/@GMAO_Shared/GMAO_etc/CMakeFiles/zeit_ci.x.dir/all] Error 2
> [ 29%] Built target NCEP_bufr_r8i8

...

This part of code has not been the focus of my development, so I had kind of ignored these crashes for sometime.  If I marked off relevant CMakeLists.txt file statements, similar errors would occur at later steps. 

Any idea what I did wrong?

**Comment by tclune** [comment]
Can you post the full (serial) build log?   The primary error is undoubtedly before the lines that you report above.    Easiest way to do this is to go into your existing build dir and do a make clean and then `make` (with no `-j` option) and piping the output to  a file.  (Shell dependent.)

**Comment by mathomp4** [comment]
I just cloned GEOSadas v5.29.0.1 and I can build it just fine. The error you are seeing seems more in my mind to be a "Intel having a bad day" or "running out of inodes" sort of thing (i.e., it's so weird, I have to think it's something funky on discover).

So, first, can you make sure you aren't near the inodes limit on the file system you are building on? If that looks fine, can you try building again?

If you still get crashes, then we might have to start looking at your environment and seeing if there is something different there.

**Comment by mathomp4** [comment]
@jing-guo An update. I'm thinking you have found a fancy new issue. I found your build at:
```
/discover/nobackup/jguo/_github_/GEOS-ESM/GEOSadas,new
```
and realized you had commas in places I've never used. So I tried building in a directory that contained a comma:
```
build,Release
```
instead of my default:
```
build-Release
```
and it failed in a similar way.

Until we can figure this out (I'm guessing CMake is maybe handling commas in a weird way?), do you think you can try to use a path with no commas in the directory tree? Maybe that will get you around this.

**Comment by jing-guo** [comment]
Thank you all.  Sorry I spent most of my time either working with underneath git environment or emails, not very familiar with gitHub web interfaces to quickly track the discussion.  That is, until today I decided to spend some time to familiar myself with new github web interfaces and processes, which is certainly more colorful than I had realized.   

In particular thank your analysis nailed down the source of my problem with only limited information.  Yes, the cause is indeed my long time practice of naming my git-clones (or cvs-checkouts) with a comma lead ",xxx" suffix, indicating objective or status of a local repo, and to help my shell tools to identify the true remote repo source from an actual  clone name.  I also finally cornered that source of problem at the end of the last week.  Wish I had read your discussion earlier. 

It is not a problem for me to change my long time habit to workaround this problem.  I will figure out another suffix to serve shell tools I have.

For Tom's concern of lacking information between lines.  I agree.  But I am also wondering if our build log is too clean by its default configuration.  For example, NOAA-EMC/GSI would by default, explicitly produce all command lines of $(FC) -c or $(FC)  -o in full.  So one can simply relate those of failed commands in their local details.  I tried different cmake options I know of to turn that on, but was not able to do so.

**Comment by mathomp4** [comment]
> Thank you all. Sorry I spent most of my time either working with underneath git environment or emails, not very familiar with gitHub web interfaces to quickly track the discussion. That is, until today I decided to spend some time to familiar myself with new github web interfaces and processes, which is certainly more colorful than I had realized.
> 
> In particular thank your analysis nailed down the source of my problem with only limited information. Yes, the cause is indeed my long time practice of naming my git-clones (or cvs-checkouts) with a comma lead ",xxx" suffix, indicating objective or status of a local repo, and to help my shell tools to identify the true remote repo source from an actual clone name. I also finally cornered that source of problem at the end of the last week. Wish I had read your discussion earlier.
> 
> It is not a problem for me to change my long time habit to workaround this problem. I will figure out another suffix to serve shell tools I have.
> 
> For Tom's concern of lacking information between lines. I agree. But I am also wondering if our build log is too clean by its default configuration. For example, NOAA-EMC/GSI would by default, explicitly produce all command lines of $(FC) -c or $(FC) -o in full. So one can simply relate those of failed commands in their local details. I tried different cmake options I know of to turn that on, but was not able to do so.

@jing-guo If you want to see the actual commands, you can do:
```
make install VERBOSE=1
```
which will turn off everything CMake hides. So this:
```
[100%] Linking Fortran executable ../../../bin/GEOSgcm.x
[100%] Built target GEOSgcm.x
```
say becomes:
```
[100%] Linking Fortran executable ../../../bin/GEOSgcm.x
cd /discover/swdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release/src/Applications/@GEOSgcm_App && /gpfsm/dulocal/sles12/other/cmake/3.21.0/bin/cmake -E remove /discover/swdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release/bin/GEOSgcm.x
cd /discover/swdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release/src/Applications/@GEOSgcm_App && /gpfsm/dulocal/sles12/other/cmake/3.21.0/bin/cmake -E cmake_link_script CMakeFiles/GEOSgcm.x.dir/link.txt --verbose=1
/usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort     -Wl,--disable-new-dtags -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release -Xlinker -rpath -Xlinker /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib -O3 -g -xCORE-AVX2 -fma -qopt-report0 -ftz -align all -fno-alias -align array32byte -traceback -assume realloc_lhs -fpe3 -fp-model consistent -assume noold_maxminloc -align dcommons CMakeFiles/GEOSgcm.x.dir/GEOSgcm.F90.o -o ../../../bin/GEOSgcm.x   -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib  -Wl,-rpath,/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib:/discover/swdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release/lib: ../../../lib/libGEOSgcm_GridComp.a ../../../lib/libGEOSagcm_GridComp.a ../../../lib/libGEOSsuperdyn_GridComp.a ../../../lib/libGEOSdatmodyn_GridComp.a ../../../lib/libGEOSphysics_GridComp.a ../../../lib/libGMAO_stoch.a ../../../lib/libGMAO_transf.a ../../../lib/libNCEP_bufr_r4i4.a ../../../lib/libNCEP_w3_r8i4.a ../../../lib/libNCEP_sigio.a ../../../lib/libNCEP_sfcio.a ../../../lib/libNCEP_bacio_r4i4.a ../../../lib/libGEOSchem_GridComp.a ../../../lib/libGOCART_GridComp.a ../../../lib/libO3_GridComp.a ../../../lib/libCO_GridComp.a ../../../lib/libCO2_GridComp.a ../../../lib/libCFC_GridComp.a ../../../lib/libDU_GridComp.a ../../../lib/libSS_GridComp.a ../../../lib/libBC_GridComp.a ../../../lib/libOC_GridComp.a ../../../lib/libSU_GridComp.a ../../../lib/libRn_GridComp.a ../../../lib/libCH4_GridComp.a ../../../lib/libNI_GridComp.a ../../../lib/libBRC_GridComp.a ../../../lib/libGEOSpchem_GridComp.a ../../../lib/libStratChem_GridComp.a ../../../lib/libGMIchem_GridComp.a ../../../lib/libCARMAchem_GridComp.a ../../../lib/libGEOSCHEMchem_GridComp.a ../../../lib/libMATRIXchem_GridComp.a ../../../lib/libMAMchem_GridComp.a ../../../lib/libGAAS_GridComp.a ../../../lib/libTR_GridComp.a ../../../lib/libGEOSachem_GridComp.a ../../../lib/libDNA_GridComp.a ../../../lib/libHEMCO_GridComp.a ../../../lib/libHEMCO.a ../../../lib/libGEOSmoist_GridComp.a ../../../lib/libChem_Shared.a ../../../lib/libChem_Base.a ../../../lib/libGMAO_gfio_r4.a ../../../lib/libGEOSsurface_GridComp.a ../../../lib/libGEOSlandice_GridComp.a ../../../lib/libGEOSlake_GridComp.a ../../../lib/libGEOSland_GridComp.a ../../../lib/libGEOSvegdyn_GridComp.a ../../../lib/libGEOScatch_GridComp.a ../../../lib/libGEOScatchCN_GridComp.a ../../../lib/libGEOS_LandShared.a ../../../lib/libGEOS_SurfaceShared.a ../../../lib/libGEOSroute_GridComp.a ../../../lib/libGEOSsaltwater_GridComp.a ../../../lib/libGEOSturbulence_GridComp.a ../../../lib/libGEOSgwd_GridComp.a ../../../lib/libGEOSradiation_GridComp.a ../../../lib/libGEOSsolar_GridComp.a ../../../lib/libRRTMG_SW.a ../../../lib/libRRTMG_SW_mods.a ../../../lib/libGEOSirrad_GridComp.a ../../../lib/libRRTMGP.a ../../../lib/libRRTMG.a ../../../lib/libRRTMG_mods.a ../../../lib/libGEOSsatsim_GridComp.a ../../../lib/libGEOS_RadiationShared.a ../../../lib/libGEOSdataatm_GridComp.a ../../../lib/libGEOSmkiau_GridComp.a ../../../lib/libNCEP_sp_r4i4.a ../../../lib/libNCEP_w3_r4i4.a /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_intel_lp64.so /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_sequential.so /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_core.so ../../../lib/libFVdycoreCubed_GridComp.a ../../../lib/libGEOS_Shared.a ../../../lib/libGMAO_hermes.a ../../../lib/libGMAO_gfio_r8.a ../../../lib/libGMAO_mpeu.a ../../../lib/libfvdycore.a ../../../lib/libfms_r8.so ../../../lib/libGEOSogcm_GridComp.a ../../../lib/libGuestOcean_GridComp.a ../../../lib/libGEOSdatasea_GridComp.a ../../../lib/libGEOS_Seaice_GridComp.a ../../../lib/libGEOSdataseaice_GridComp.a ../../../lib/libGEOSCICEDyna_GridComp.a ../../../lib/libCICE4.a ../../../lib/libGEOS_OceanBioGeoChemGridComp.a ../../../lib/libGEOS_OradGridComp.a ../../../lib/libGEOS_OradBioGridComp.a ../../../lib/libMAPL.so ../../../lib/libMAPL.gridcomps.so ../../../lib/libMAPL.cap.so ../../../lib/libMAPL.history.so ../../../lib/libMAPL.base.so ../../../lib/libMAPL.pfio.so ../../../lib/libMAPL_cfio_r4.so ../../../lib/libMAPL.generic.so ../../../lib/libMAPL.profiler.so ../../../lib/libMAPL.shared.so /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/PFLOGGER-1.5/lib/libpflogger.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/YAFYAML-0.5/lib/libyafyaml.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/GFTL_SHARED-1.3/lib/libgftl-shared-v1.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib/libesmf.so /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/libmpicxx.so /usr/local/other/gcc/8.3.0/lib64/../lib64/libstdc++.so /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib/libnetcdff.a -lnetcdff -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lsz -ljpeg -lgpfs -ldl -lcurl -lssl -lcrypto -lz -lm -pthread /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/libmpifort.so /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release/libmpi.so /usr/lib64/libdl.so /usr/lib64/librt.so -lpthread /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib64/libFLAP.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib64/libFACE.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib64/libPENF.a /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64/libiomp5.so -lirng -ldecimal -lcilkrts -lstdc++
make[3]: Leaving directory '/gpfsm/dswdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release'
[100%] Built target GEOSgcm.x
make[2]: Leaving directory '/gpfsm/dswdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release'
/gpfsm/dulocal/sles12/other/cmake/3.21.0/bin/cmake -E cmake_progress_start /discover/swdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release/CMakeFiles 0
make[1]: Leaving directory '/gpfsm/dswdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release'
```
So...much more verbose!

Note that goes a loooooong way to the right. On a terminal it'll like:

/usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort     -Wl,--disable-new-dtags -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release -Xlinker -rpath -Xlinker /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib -O3 -g -xCORE-AVX2 -fma -qopt-report0 -ftz -align all -fno-alias -align array32byte -traceback -assume realloc_lhs -fpe3 -fp-model consistent -assume noold_maxminloc -align dcommons CMakeFiles/GEOSgcm.x.dir/GEOSgcm.F90.o -o ../../../bin/GEOSgcm.x   -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib  -Wl,-rpath,/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib:/discover/swdev/mathomp4/Models/GEOSgcm-Presets/GEOSgcm/build-Release/lib: ../../../lib/libGEOSgcm_GridComp.a ../../../lib/libGEOSagcm_GridComp.a ../../../lib/libGEOSsuperdyn_GridComp.a ../../../lib/libGEOSdatmodyn_GridComp.a ../../../lib/libGEOSphysics_GridComp.a ../../../lib/libGMAO_stoch.a ../../../lib/libGMAO_transf.a ../../../lib/libNCEP_bufr_r4i4.a ../../../lib/libNCEP_w3_r8i4.a ../../../lib/libNCEP_sigio.a ../../../lib/libNCEP_sfcio.a ../../../lib/libNCEP_bacio_r4i4.a ../../../lib/libGEOSchem_GridComp.a ../../../lib/libGOCART_GridComp.a ../../../lib/libO3_GridComp.a ../../../lib/libCO_GridComp.a ../../../lib/libCO2_GridComp.a ../../../lib/libCFC_GridComp.a ../../../lib/libDU_GridComp.a ../../../lib/libSS_GridComp.a ../../../lib/libBC_GridComp.a ../../../lib/libOC_GridComp.a ../../../lib/libSU_GridComp.a ../../../lib/libRn_GridComp.a ../../../lib/libCH4_GridComp.a ../../../lib/libNI_GridComp.a ../../../lib/libBRC_GridComp.a ../../../lib/libGEOSpchem_GridComp.a ../../../lib/libStratChem_GridComp.a ../../../lib/libGMIchem_GridComp.a ../../../lib/libCARMAchem_GridComp.a ../../../lib/libGEOSCHEMchem_GridComp.a ../../../lib/libMATRIXchem_GridComp.a ../../../lib/libMAMchem_GridComp.a ../../../lib/libGAAS_GridComp.a ../../../lib/libTR_GridComp.a ../../../lib/libGEOSachem_GridComp.a ../../../lib/libDNA_GridComp.a ../../../lib/libHEMCO_GridComp.a ../../../lib/libHEMCO.a ../../../lib/libGEOSmoist_GridComp.a ../../../lib/libChem_Shared.a ../../../lib/libChem_Base.a ../../../lib/libGMAO_gfio_r4.a ../../../lib/libGEOSsurface_GridComp.a ../../../lib/libGEOSlandice_GridComp.a ../../../lib/libGEOSlake_GridComp.a ../../../lib/libGEOSland_GridComp.a ../../../lib/libGEOSvegdyn_GridComp.a ../../../lib/libGEOScatch_GridComp.a ../../../lib/libGEOScatchCN_GridComp.a ../../../lib/libGEOS_LandShared.a ../../../lib/libGEOS_SurfaceShared.a ../../../lib/libGEOSroute_GridComp.a ../../../lib/libGEOSsaltwater_GridComp.a ../../../lib/libGEOSturbulence_GridComp.a ../../../lib/libGEOSgwd_GridComp.a ../../../lib/libGEOSradiation_GridComp.a ../../../lib/libGEOSsolar_GridComp.a ../../../lib/libRRTMG_SW.a ../../../lib/libRRTMG_SW_mods.a ../../../lib/libGEOSirrad_GridComp.a ../../../lib/libRRTMGP.a ../../../lib/libRRTMG.a ../../../lib/libRRTMG_mods.a ../../../lib/libGEOSsatsim_GridComp.a ../../../lib/libGEOS_RadiationShared.a ../../../lib/libGEOSdataatm_GridComp.a ../../../lib/libGEOSmkiau_GridComp.a ../../../lib/libNCEP_sp_r4i4.a ../../../lib/libNCEP_w3_r4i4.a /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_intel_lp64.so /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_sequential.so /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_core.so ../../../lib/libFVdycoreCubed_GridComp.a ../../../lib/libGEOS_Shared.a ../../../lib/libGMAO_hermes.a ../../../lib/libGMAO_gfio_r8.a ../../../lib/libGMAO_mpeu.a ../../../lib/libfvdycore.a ../../../lib/libfms_r8.so ../../../lib/libGEOSogcm_GridComp.a ../../../lib/libGuestOcean_GridComp.a ../../../lib/libGEOSdatasea_GridComp.a ../../../lib/libGEOS_Seaice_GridComp.a ../../../lib/libGEOSdataseaice_GridComp.a ../../../lib/libGEOSCICEDyna_GridComp.a ../../../lib/libCICE4.a ../../../lib/libGEOS_OceanBioGeoChemGridComp.a ../../../lib/libGEOS_OradGridComp.a ../../../lib/libGEOS_OradBioGridComp.a ../../../lib/libMAPL.so ../../../lib/libMAPL.gridcomps.so ../../../lib/libMAPL.cap.so ../../../lib/libMAPL.history.so ../../../lib/libMAPL.base.so ../../../lib/libMAPL.pfio.so ../../../lib/libMAPL_cfio_r4.so ../../../lib/libMAPL.generic.so ../../../lib/libMAPL.profiler.so ../../../lib/libMAPL.shared.so /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/PFLOGGER-1.5/lib/libpflogger.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/YAFYAML-0.5/lib/libyafyaml.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/GFTL_SHARED-1.3/lib/libgftl-shared-v1.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib/libesmf.so /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/libmpicxx.so /usr/local/other/gcc/8.3.0/lib64/../lib64/libstdc++.so /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib/libnetcdff.a -lnetcdff -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lsz -ljpeg -lgpfs -ldl -lcurl -lssl -lcrypto -lz -lm -pthread /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/libmpifort.so /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release/libmpi.so /usr/lib64/libdl.so /usr/lib64/librt.so -lpthread /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib64/libFLAP.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib64/libFACE.a /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.4/x86_64-pc-linux-gnu/ifort_19.1.3.304-intelmpi_19.1.3.304/Linux/lib64/libPENF.a /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64/libiomp5.so -lirng -ldecimal -lcilkrts -lstdc++

**Comment by tclune** [comment]
And you can do this for specific targets if you don't want to see it for the whole model.  (But you'll still see it for any out of date dependencies of said target.)

**Comment by jing-guo** [comment]
Great!  I consider this issue has resolved, and close it for now.
