### ISSUE TITLE
GEOSadas does not build and will not run GSI when using cmake "DEBUG" build type.

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSadas#118]
While trying to track a crash in the GSIsa.x I decided to see what the status of the "DEBUG" build type is in CMAKE using the rt-GEOSadas-5_29_2 tag. I found that it neither builds, nor does the GSIsa.x run successfully. I will summarize here.
First the build
1.) At least until Intel 19 (maybe fixed in 2021) there is a persistent random ICE when building  Ada_Module.F90 in NCEP_CRTM and seems to occur all the time with the DEBUG flags, we find that for whatever reason O1 optimization level always works.
2.) There is a file in GEOSaana_GridComp/GSI_GridComp/prepbykx.f that because of the tricks needed to get zero diff in the CMakeLists.txt was not getting extended source flag passed when building with "DEBUG" build type so the either cmakefile file needs to be fixed or the prebpykx.f needs to be fixed to break that line up.

Then when running GSIsa.x several errors occurred that were discovered as the previous one was fixed, all in the GSI_GridCompMod.F90
First on line 2714:
 ``` 
call ArrayScatter(vfrp, vfrbuf, GSIGrid, hw=hw, rc=STATUS)
```
If you look up above vfrbug and several other variables are only allocated on root. If the array is not allocated on the other processors this causes an error since you are using an unallocated array. So in the if (am root) section above you need to have an else and allocate
Allocate(vfrbuf(0,0))
Along with the  other variables that are allocated in the same statement

Second on line 2648 which looks like so:
```
sfcbuf=data%vfrac
``` 
it was crashing and saying that data%vdata is not associated so that needs to be protect with an if associated construct.

Finally after fixing those it fails with a divide by zero: 
```
GSI_GridCompCopyImportSfc2Internal_
 : Copy contents of import to internal state, it=            1
[000]GSI_GridCompCopyImportSfc2Internal_(): reset ntguessfc, (from, to) = 4 4
 GSI_GridCompGetNCEPsfcFromFile_: Using sfcio to read NCEP surface file (as BC)
 GSI_GridCompGetNCEPsfcFromFile_: ncepsfc hour/date  :   0.0000000E+00  /
           0           0           0           0
 GSI_GridCompGetNCEPsfcFromFile_: ncepsfc fields dims, version:            0  x
           0  v           0
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source
GSIsa.x            000000001002065B  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAC1398C10  Unknown               Unknown  Unknown
libMAPL.shared.so  00002AAABE304809  hinterp2_                  16  hinterp.F
GSIsa.x            0000000000574761  gsi_gridcompmodru        2652  GSI_GridCompMod.F90
GSIsa.x            00000000004E9B53  gsi_gridcompmod_m        1375  GSI_GridCompMod.F90
```
That's what I've found so far.

**Comment by rtodling** [comment]
Ben, are you know able to compile/run GSI w/ debug on? Can we close this, or do we still have problems?
