### ISSUE TITLE
Ricardo: Gather a BSLN experiment

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSadas#153]
Ricardo: points us/gathers or _saves_ a "long" lived x-exp (atmospheric DA at C360)

**Comment by sanAkel** [comment]
/discover/nobackup/projects/gmao/dadev/rtodling/archive/Restarts/x0045/rs/Y2020/M11/x0045.rst.20201129_21z.tar

**Comment by rtodling** [comment]
Script pointing to BCS:

/discover/nobackup/projects/gmao/dadev/dao_it/Winter_Runs/x0045a/run/lnbcs

**Comment by sanAkel** [comment]
Hi @atrayano please see above documentation. Thanks!
