### ISSUE TITLE
Update write_monthly_rc_arc.pl script to add hourtype for traj_lcv_rst to monthly.rc 

### ISSUE THREAD

**Issue by gmao-jstassi** [GEOS-ESM/GEOSadas#177]
The monthly processing is unable to deduce the hourtype for traj_lcv_rst from the collection name, so the hourtype needs to be added to the monthly.rc file.

**Comment by rtodling** [comment]
Far as I know this is done

**Comment by rtodling** [comment]
See GEOSadas-5.29.4-p1
