### ISSUE TITLE
Crash in prepQC raobcore.x in v5.25.0

### ISSUE THREAD

**Issue by gmao-msienkie** [GEOS-ESM/GEOSadas#43]
/gpfsm/dnb04/projects/p72/msienkie/v5.25.0/GEOSadas/install/bin/gmao_prepqc: raobcore.x -o raobcor.%y4%m2%d2.%h2 -r /discover/nobackup/projects/gmao/obsdev/msienkie/g008_C180/fvInput/preproc/racor/biascor-1.4r.txt /gpfsm/dnb04/projects/p72/msienkie/fvwork.12302/prepqc.20180222.00/next.20180222.00
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
raobcore.x         00000000004B728E  Unknown               Unknown  Unknown
libpthread-2.11.3  00002AAAAB8D8850  Unknown               Unknown  Unknown
raobcore.x         0000000000475B76  m_ellipsoid_mp_di         801  m_ellipsoid.f
raobcore.x         000000000045F60E  m_soundings_mp_ll         531  m_soundings.f
raobcore.x         0000000000427BB5  m_raddata_mp_setd         538  m_RadData.f
raobcore.x         000000000040A5A4  MAIN__                    142  raobcore.f
raobcore.x         000000000040925E  Unknown               Unknown  Unknown
libc-2.11.3.so     00002AAAABD09C36  __libc_start_main     Unknown  Unknown
raobcore.x         00000000004090E9  Unknown               Unknown  Unknown
>>>> ERROR <<< running raobcore.x at /gpfsm/dnb04/projects/p72/msienkie/v5.25.0/GEOSadas/install/bin/gmao_prepqc line 508.

The program was able to run without crashing in the CVS 5_25_0 and the code has been running (with only slight modification) since MERRA.  Maybe a compilation difference?

**Comment by tclune** [comment]
@gmao-msienkie Do you think this is possibly related to the Git transition?   If so, please assign members of the SI team to investigate.  (bena-nasa and mathomp4)

**Comment by gmao-msienkie** [comment]
It could be related, if the new build is done with different settings.
My initial purpose is documenting that this component is broken - luckily most of our work (except for reanalysis folks) doesn't involve running the prepQC (NCEP_Paqc).  
I will add Ben and Matt to the issue so one of them could look at the build.  I can supply an example for testing.
I will be looking at the code (along with my testing the NRL aircraft QC under git/CMake) -in case the new build exposed a problem that had been hiding all these years...

**Comment by gmao-msienkie** [comment]
Here is a clue to the crash.  The first sounding in both the files I tested is at the South Pole.  When I created another file with just one sounding from a different station, the program was able to run without the floating invalid error.  The crash is in a formula for calculating distance on a sphere, when the program is recalculating balloon drift from the station.  I imagine if there is going to be a problem, you would have it for a calculation at the North or South Pole.

**Comment by gmao-msienkie** [comment]
Line 801 in m_ellipsoid.f90 (subroutine DirSph)
xsq  = sina ** 2 + ( sinU1 * sins - cosU1 * coss * cosa12 ) ** 2

At the South Pole the first term (sina) is essentially zero - latitude is -90, sina=cos(lat)*sin(azimuth) but I imagine it evaluates to a very small term instead and I guess the square of that small term trips the 'floating invalid' error.  Perhaps the compilation is more stringent wrt. floating point numbers than before.

**Comment by mathomp4** [comment]
@gmao-msienkie,

First, do you mean `m_ellipsoid.f`? I cannot find a `.f90` file with that name in our codebase.

Second, I'm pretty sure the compiler options are fundamentally the same. In CVS:
```
-O2
-r8 -i8
-fPIC
-extend_source
-fpe0
-fp-model source
-heap-arrays 32
-assume noold_maxminloc
-fimf-arch-consistency=true
-align dcommons
```
and in CMake:
```
-O2
-g
-traceback
-assume realloc_lhs
-fpe0
-fp-model source
-heap-arrays 32
-assume noold_maxminloc
-fimf-arch-consistency=true
-align dcommons
-fPIC 
-r8 -i8
```
Now, we do have `-g -traceback -assume realloc_lhs` in CMake. It's possible this could cause an change, but I'd be surprised as it never has before. But the main options are in the same order so it should make the same code in the end.

And, we don't have `-extend_source` but that almost always is only needed if it can't compile so I didn't spread it everywhere.

**Comment by gmao-msienkie** [comment]
That should be m_ellipsoid.f - sorry.
I was able to get the program to run if I pre-calculated the two terms in the equation on line 801 and then calculated xsq.  However, your comments prompted me to double-check.

The problem actually is - it needs to be compiled '-extend-source' !  It didn't fail compiling but the last part of the line " **2 " was cut off.  I haven't tested this yet but given what I found above it would probably work.

**Comment by gmao-msienkie** [comment]
I tried splitting the equation on line 801 onto two lines.  Testing this with my checkout of v5.25.0, it ran without a problen and produced zero diff to the BUFR files created by running executables in ~dao_ops/GEOSadas-5_25_1.  
I see two choices - 1) go with splitting the line and trust that other routines in the directory do not have too-long lines in the code that still appears to compile OR 2) add the -extend_source to the CMakefile.
