### ISSUE TITLE
Crash in gmao_prevents.x for MERRA2 prepbufr after 10-22-2020

### ISSUE THREAD

**Issue by gmao-msienkie** [GEOS-ESM/GEOSadas#49]
NCEP modified their processing to add surface marine data processed from BUFR input on 10/22/2020.  The 'prepdata.x' program used to produce the MERRA2 prepbufr files at NCEP had to be updated, and it would have been compiled with a new BUFRLIB.  The new version of prepdata.x writes latitude/longitude at higher precision than before.  Somehow between the updates prepdata.x and the BUFR library, the representation of latitude for South Pole observations (cast from R*8->R*4) changed so that it was very slightly less than 90.00 S.  This caused a crash in the interpolation routine, trying to access outside of the array.  The routine is being patched to set the minimum N-S array index to 1 when performing the interpolation.

**Comment by gmao-msienkie** [comment]
Created branch bugfix/msienkie/#49-SP-interp-crash with modified code in NCEP_Paqc/GMAOprev/gblevents_gmao.f

**Comment by mathomp4** [comment]
@gmao-msienkie Is this something we should get into our upcoming Git-version-of-GEOSadas-5_27_1 version of GEOSadas? Or is it a possible non-zero-diff thing that is better to have wait until after that release?

**Comment by gmao-msienkie** [comment]
Since the regular FP runs and most experiments that people run will be using the operational GDAS prepbufr files and not running the preprocessing QC.  So they are not affected by this change.  Maybe your system tests didn't include running with prepQC either.
I believe that prior to the data change on 10/22/2020 that this change will be zero-diff.  (I ran a couple tests just before the date to check.)  So this particular patch does not become an issue until people start running the preprocessing QC for dates after 10/22/2020.  
I am hoping to get Ricardo to take this into a tag as soon as possible because it will (eventually) be relevant to reanalysis runs. 
I'd just like to get this change in eventually - but maybe it would be better to have it in a system before lots of people check it out and start basing their experiments on it.

**Comment by mathomp4** [comment]
Well, let us ping @rtodling here and see if he responds. We could add it to v5.27.1 or wait until the next tag. Either way, it's good to know the code is here!

**Comment by gmao-msienkie** [comment]
I have added this change to a catch-all branch with various modifications for PAQC (not including the NRL ACQC that we also need to bring in to the DAS).
