### ISSUE TITLE
mkiau.x produces bad agcm_import_rst using latest model version in the GEOSfixture.

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSadas#54]
Proactive note to remember an issue needed to be addressed as we move the model version forward from the initial 5_27_1 version.
During my testing of taking the 5_27_1 candidate of the GEOSadas fixture to use the latest version of the libraries (GEOSgcm_GridComp etc) after fixing the other setup issues (#50, #51, #52, #53) the model runs 3 hours before segfaulting in radiation. If no agcm_import_rst is specified (i.e. no increment applied) the model runs fine. Wildly speculating, perhaps related to changes I see in the GEOSagcm_GridComp.F90 version in the 5_27_1 candidate tag related to the increment handling that are not in the latest version of the GEOSgcm_GridComp repository? Just noting here for my memory.

**Comment by bena-nasa** [comment]
A further development. I compared the agcm_import_produced by the stock code vs my attempt to update the libraries.
In the file from the stock code I see this when examining the values
```
 0    13824       0 :     -9.3998   -0.029315      6.6830 : DTSDT
```
vs my updated library version
```
0    13824       0 : -1.0318e+05     -24225.      51.908 : DTSDT
```
That probably explains it. Will try to figure out what is happening.

**Comment by mathomp4** [comment]
@bena-nasa These are `cdo infon` outputs? So the fp numbers are min/mean/max values, right?

**Comment by bena-nasa** [comment]
Yes, that was the most egregious example. Something clearly went wrong. My first guess is mkiau_GridComp.

**Comment by bena-nasa** [comment]
I'm thinking this is a case of the iau grid comp and mkiau.F90 generate nx/ny differently. I'm modifying mkiau.F90 to compute nx/ny like the grid comp now does.

**Comment by bena-nasa** [comment]
Yep, that was it, just an inconsistency with the IAU grid comp and mkaiu.F90 in the nx/ny used. The solution is to use MAPL_MakeDecomposition in mkiau.F90
I will keep this issue open for now so we don't forget this when the ADAS moves to using newer versions of the IAU grid comp

**Comment by rtodling** [comment]
Is this still an issue? Do we have a problem running IAU that is going unnoticed. This is unclear to me!

**Comment by bena-nasa** [comment]
It appears to be fixed. If I look in the develop branch of the GEOSadas fixture and look in mkiau.F90 I see it call MAPL_MakeDecomposition as I suggested so I must have done this when we were making the git tag for the ADAS.

**Comment by bena-nasa** [comment]
I'm closing this issue as it has been fixed
