### ISSUE TITLE
Fix for mispositioned fixed buoy

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/GEOSadas#62]
This is to address the issue found by Gary, Meta and others above ship observation on the North Pole.

**Comment by gmao-msienkie** [comment]
A quick scan/grep of the prepbufr files around that time revealed:

d210_18.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 1.000,TYP= 280.,NLEV=   1
d210_18.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 1.000,TYP= 180.,NLEV=   1
d211_00.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 0.000,TYP= 280.,NLEV=   1
d211_00.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 0.000,TYP= 180.,NLEV=   1
d211_00.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 1.000,TYP= 280.,NLEV=   1
d211_00.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 1.000,TYP= 180.,NLEV=   1
d211_00.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR=-1.000,TYP= 280.,NLEV=   1
d211_00.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR=-1.000,TYP= 180.,NLEV=   1
d211_00.SFCSHP:SID=46207   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 2.000,TYP= 280.,NLEV=   1
d211_00.SFCSHP:SID=46207   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 2.000,TYP= 180.,NLEV=   1
d211_06.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 1.000,TYP= 280.,NLEV=   1
d211_06.SFCSHP:SID=46208   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR= 1.000,TYP= 180.,NLEV=   1
d211_06.SFCSHP:SID=46207   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR=-3.000,TYP= 280.,NLEV=   1
d211_06.SFCSHP:SID=46207   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR=-3.000,TYP= 180.,NLEV=   1
d211_06.SFCSHP:SID=46207   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR=-2.000,TYP= 280.,NLEV=   1
d211_06.SFCSHP:SID=46207   ,YOB= 90.00,XOB=270.00,ELV=    0.0,DHR=-2.000,TYP= 180.,NLEV=   1

**Comment by gmao-msienkie** [comment]
These observations were not flagged by the preprocessing, in part because OIQC is not run in the GDAS preprocessing any more.

**Comment by gmao-msienkie** [comment]
I checked the prepbufr output from the prepQC in MERRA2, and found that the misplaced temperature observations had been flagged by the OIQC that we're running in the preprocessing (QM=6)
[oiqc_output.txt](https://github.com/GEOS-ESM/GEOSadas/files/6093793/oiqc_output.txt)

All those obs in the GDAS prepbufr had a quality mark of 2, which is passing QC.  Only the most basic QC is performed on SFCSHP in the prepdata processing.

**Comment by gmao-msienkie** [comment]
There are two issues here.
First - observations that differ from the background by 20K are being accepted by the DAS.  Seems like the gross check parameters need to be adjusted.
Second - do we get very many of these observations?  If we're getting these kinds of obs often (e.g. maybe if lat/lon are bad or missing, it gets written as 90N at some point along the line?  Maybe something new with BUFR buoy data?) we should have something in the code to exclude obs at the North Pole.

**Comment by gmao-msienkie** [comment]
I found locations where the surface marine temperature observation (kx=180,kt=44) was at/near 90N (lat=89:90) by processing ODS files with odsselect.

foreach i ( f5271_fp.diag_conv.202102*ods )
   set dt = `echo $i | cut -d. -f3 `
   /discover/nobackup/projects/gmao/obsdev/msienkie/GEOSadas-5_27_1/GEOSadas/Linux/bin/odsselect -kx 180 \
      -kt 44 -lat 89:90 -qc ALL -o NP.$dt $i
end

I used odslist to list the selected observations from each extracted ODS time and grepped the information to make a list
[FP_NPodslist_Feb2021.txt](https://github.com/GEOS-ESM/GEOSadas/files/6132836/FP_NPodslist_Feb2021.txt)

The OmFs ranged from 11K to over 30K (even for at least one obs that passed QC).  Not all of the observations had a longitude of -90.
The smallest obs errors were around 3.  There were some obs errors over 10K.

I dumped information for SFCSHP data from the GDAS prepbufr files used in FP for the dates which had had marine observations at 90N, and grepped out the information for the observations at 90N - listed here:
[GDAS_NP180_Feb2021.txt](https://github.com/GEOS-ESM/GEOSadas/files/6132868/GDAS_NP180_Feb2021.txt)
The bad observations are from these three buoys:  46146, 46207, 46208.  However there is also good data coming from those buoys.

I did the same check on MERRA2 prepbufr files (processed through prepqc) on the same days, shown in this table
[MERRA2_NP180_Feb2021.txt](https://github.com/GEOS-ESM/GEOSadas/files/6132890/MERRA2_NP180_Feb2021.txt)
It looks like only one of these observations had a passing quality mark after the OIQC processing.

**Comment by gmao-msienkie** [comment]
It looks like less than 2% of the obs from these three stations are given wrong positions.  A bit more than 1% are given latitudes of 90N while other mispositioned obs are give longitudes of 270.  (Some have both latitude and longitude wrong.)  While there are some valid marine observations at 270 longitude there are no valid ships at 90N.  
The issue could be fixed by discarding observations at 90N, as before (but not 90S this time).   Or a simple program could be run on receipt of the data or on the fly when executing the DAS that would blacklist (QM=14) any surface marine observations (kx=180,280) with latitudes = 90N.

**Comment by gmao-msienkie** [comment]
I have tested a change that will skip over the observations from fixed buoys (TYP=180,280 T29=561).  I have tested this as a static analysis.  This change is on the branch bugfix/msienkie/badNPships

**Comment by gmao-msienkie** [comment]
I have also written a program to run externally in preprocessing, to modify the pressure QM to purge (PQM=14) fixed buoy observations with latitude = 90N. 
source: src/Applications/NCEP_Paqc/modify_bufr/flag_NPbuoy.f
branch: feature/msienkie/PAQC_modifications_v5_27_1_p3
(note there are a number of other modifications saved on the branch, to bring in various NCEP changes and other fixes)

**Comment by gmao-msienkie** [comment]
GEOSana_GridComp PR # 23 included a fix for this issue.  The code was merged in at the end of May and the PR was closed on Jun 3.
